branch-defaults:
  default:
    environment: camsite-dev
    group_suffix: null
global:
  application_name: camsite
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-1
  profile: eb-cli
  sc: null
